//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorNextGestorPDV.WSFinanceiro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSFinanceiro.wsFinanceiroSoap")]
    public interface wsFinanceiroSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento email no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornaEntidade", ReplyAction="*")]
        IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeResponse RetornaEntidade(IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornaEntidade", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeResponse> RetornaEntidadeAsync(IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEntidades", ReplyAction="*")]
        IntegradorNextGestorPDV.WSFinanceiro.getEntidadesResponse getEntidades(IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEntidades", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getEntidadesResponse> getEntidadesAsync(IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProdutos", ReplyAction="*")]
        IntegradorNextGestorPDV.WSFinanceiro.getProdutosResponse getProdutos(IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProdutos", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getProdutosResponse> getProdutosAsync(IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMarcas", ReplyAction="*")]
        IntegradorNextGestorPDV.WSFinanceiro.getMarcasResponse getMarcas(IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMarcas", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getMarcasResponse> getMarcasAsync(IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmitente", ReplyAction="*")]
        IntegradorNextGestorPDV.WSFinanceiro.getEmitenteResponse getEmitente(IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmitente", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getEmitenteResponse> getEmitenteAsync(IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsuario", ReplyAction="*")]
        IntegradorNextGestorPDV.WSFinanceiro.getUsuarioResponse getUsuario(IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getUsuarioResponse> getUsuarioAsync(IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizaVendas", ReplyAction="*")]
        IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasResponse AtualizaVendas(IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizaVendas", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasResponse> AtualizaVendasAsync(IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFormaPgto", ReplyAction="*")]
        IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoResponse getFormaPgto(IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFormaPgto", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoResponse> getFormaPgtoAsync(IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEtiquetas", ReplyAction="*")]
        IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasResponse getEtiquetas(IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEtiquetas", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasResponse> getEtiquetasAsync(IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaEntidadeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaEntidade", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequestBody Body;
        
        public RetornaEntidadeRequest() {
        }
        
        public RetornaEntidadeRequest(IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornaEntidadeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        public RetornaEntidadeRequestBody() {
        }
        
        public RetornaEntidadeRequestBody(string email, string senha) {
            this.email = email;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaEntidadeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaEntidadeResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeResponseBody Body;
        
        public RetornaEntidadeResponse() {
        }
        
        public RetornaEntidadeResponse(IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornaEntidadeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RetornaEntidadeResult;
        
        public RetornaEntidadeResponseBody() {
        }
        
        public RetornaEntidadeResponseBody(int RetornaEntidadeResult) {
            this.RetornaEntidadeResult = RetornaEntidadeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEntidadesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEntidades", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequestBody Body;
        
        public getEntidadesRequest() {
        }
        
        public getEntidadesRequest(IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEntidadesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        public getEntidadesRequestBody() {
        }
        
        public getEntidadesRequestBody(string cnpj) {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEntidadesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEntidadesResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getEntidadesResponseBody Body;
        
        public getEntidadesResponse() {
        }
        
        public getEntidadesResponse(IntegradorNextGestorPDV.WSFinanceiro.getEntidadesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEntidadesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getEntidadesResult;
        
        public getEntidadesResponseBody() {
        }
        
        public getEntidadesResponseBody(string getEntidadesResult) {
            this.getEntidadesResult = getEntidadesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProdutosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProdutos", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequestBody Body;
        
        public getProdutosRequest() {
        }
        
        public getProdutosRequest(IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProdutosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        public getProdutosRequestBody() {
        }
        
        public getProdutosRequestBody(string cnpj) {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProdutosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProdutosResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getProdutosResponseBody Body;
        
        public getProdutosResponse() {
        }
        
        public getProdutosResponse(IntegradorNextGestorPDV.WSFinanceiro.getProdutosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProdutosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getProdutosResult;
        
        public getProdutosResponseBody() {
        }
        
        public getProdutosResponseBody(string getProdutosResult) {
            this.getProdutosResult = getProdutosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMarcasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMarcas", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequestBody Body;
        
        public getMarcasRequest() {
        }
        
        public getMarcasRequest(IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMarcasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        public getMarcasRequestBody() {
        }
        
        public getMarcasRequestBody(string cnpj) {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMarcasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMarcasResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getMarcasResponseBody Body;
        
        public getMarcasResponse() {
        }
        
        public getMarcasResponse(IntegradorNextGestorPDV.WSFinanceiro.getMarcasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMarcasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMarcasResult;
        
        public getMarcasResponseBody() {
        }
        
        public getMarcasResponseBody(string getMarcasResult) {
            this.getMarcasResult = getMarcasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmitenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmitente", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequestBody Body;
        
        public getEmitenteRequest() {
        }
        
        public getEmitenteRequest(IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmitenteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        public getEmitenteRequestBody() {
        }
        
        public getEmitenteRequestBody(string cnpj) {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmitenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmitenteResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getEmitenteResponseBody Body;
        
        public getEmitenteResponse() {
        }
        
        public getEmitenteResponse(IntegradorNextGestorPDV.WSFinanceiro.getEmitenteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmitenteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getEmitenteResult;
        
        public getEmitenteResponseBody() {
        }
        
        public getEmitenteResponseBody(string getEmitenteResult) {
            this.getEmitenteResult = getEmitenteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsuario", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequestBody Body;
        
        public getUsuarioRequest() {
        }
        
        public getUsuarioRequest(IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        public getUsuarioRequestBody() {
        }
        
        public getUsuarioRequestBody(string cnpj) {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getUsuarioResponseBody Body;
        
        public getUsuarioResponse() {
        }
        
        public getUsuarioResponse(IntegradorNextGestorPDV.WSFinanceiro.getUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUsuarioResult;
        
        public getUsuarioResponseBody() {
        }
        
        public getUsuarioResponseBody(string getUsuarioResult) {
            this.getUsuarioResult = getUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizaVendasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizaVendas", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequestBody Body;
        
        public AtualizaVendasRequest() {
        }
        
        public AtualizaVendasRequest(IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizaVendasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string chave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string json;
        
        public AtualizaVendasRequestBody() {
        }
        
        public AtualizaVendasRequestBody(string cnpj, string chave, string json) {
            this.cnpj = cnpj;
            this.chave = chave;
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizaVendasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizaVendasResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasResponseBody Body;
        
        public AtualizaVendasResponse() {
        }
        
        public AtualizaVendasResponse(IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizaVendasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AtualizaVendasResult;
        
        public AtualizaVendasResponseBody() {
        }
        
        public AtualizaVendasResponseBody(string AtualizaVendasResult) {
            this.AtualizaVendasResult = AtualizaVendasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFormaPgtoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFormaPgto", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequestBody Body;
        
        public getFormaPgtoRequest() {
        }
        
        public getFormaPgtoRequest(IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFormaPgtoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        public getFormaPgtoRequestBody() {
        }
        
        public getFormaPgtoRequestBody(string cnpj) {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFormaPgtoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFormaPgtoResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoResponseBody Body;
        
        public getFormaPgtoResponse() {
        }
        
        public getFormaPgtoResponse(IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFormaPgtoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFormaPgtoResult;
        
        public getFormaPgtoResponseBody() {
        }
        
        public getFormaPgtoResponseBody(string getFormaPgtoResult) {
            this.getFormaPgtoResult = getFormaPgtoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEtiquetasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEtiquetas", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequestBody Body;
        
        public getEtiquetasRequest() {
        }
        
        public getEtiquetasRequest(IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEtiquetasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        public getEtiquetasRequestBody() {
        }
        
        public getEtiquetasRequestBody(string cnpj) {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEtiquetasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEtiquetasResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasResponseBody Body;
        
        public getEtiquetasResponse() {
        }
        
        public getEtiquetasResponse(IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEtiquetasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getEtiquetasResult;
        
        public getEtiquetasResponseBody() {
        }
        
        public getEtiquetasResponseBody(string getEtiquetasResult) {
            this.getEtiquetasResult = getEtiquetasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsFinanceiroSoapChannel : IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsFinanceiroSoapClient : System.ServiceModel.ClientBase<IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap>, IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap {
        
        public wsFinanceiroSoapClient() {
        }
        
        public wsFinanceiroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsFinanceiroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFinanceiroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFinanceiroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeResponse IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.RetornaEntidade(IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequest request) {
            return base.Channel.RetornaEntidade(request);
        }
        
        public int RetornaEntidade(string email, string senha) {
            IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequestBody();
            inValue.Body.email = email;
            inValue.Body.senha = senha;
            IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeResponse retVal = ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).RetornaEntidade(inValue);
            return retVal.Body.RetornaEntidadeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeResponse> IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.RetornaEntidadeAsync(IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequest request) {
            return base.Channel.RetornaEntidadeAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeResponse> RetornaEntidadeAsync(string email, string senha) {
            IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.RetornaEntidadeRequestBody();
            inValue.Body.email = email;
            inValue.Body.senha = senha;
            return ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).RetornaEntidadeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorNextGestorPDV.WSFinanceiro.getEntidadesResponse IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getEntidades(IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequest request) {
            return base.Channel.getEntidades(request);
        }
        
        public string getEntidades(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequestBody();
            inValue.Body.cnpj = cnpj;
            IntegradorNextGestorPDV.WSFinanceiro.getEntidadesResponse retVal = ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getEntidades(inValue);
            return retVal.Body.getEntidadesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getEntidadesResponse> IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getEntidadesAsync(IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequest request) {
            return base.Channel.getEntidadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getEntidadesResponse> getEntidadesAsync(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getEntidadesRequestBody();
            inValue.Body.cnpj = cnpj;
            return ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getEntidadesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorNextGestorPDV.WSFinanceiro.getProdutosResponse IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getProdutos(IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequest request) {
            return base.Channel.getProdutos(request);
        }
        
        public string getProdutos(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequestBody();
            inValue.Body.cnpj = cnpj;
            IntegradorNextGestorPDV.WSFinanceiro.getProdutosResponse retVal = ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getProdutos(inValue);
            return retVal.Body.getProdutosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getProdutosResponse> IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getProdutosAsync(IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequest request) {
            return base.Channel.getProdutosAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getProdutosResponse> getProdutosAsync(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getProdutosRequestBody();
            inValue.Body.cnpj = cnpj;
            return ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getProdutosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorNextGestorPDV.WSFinanceiro.getMarcasResponse IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getMarcas(IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequest request) {
            return base.Channel.getMarcas(request);
        }
        
        public string getMarcas(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequestBody();
            inValue.Body.cnpj = cnpj;
            IntegradorNextGestorPDV.WSFinanceiro.getMarcasResponse retVal = ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getMarcas(inValue);
            return retVal.Body.getMarcasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getMarcasResponse> IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getMarcasAsync(IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequest request) {
            return base.Channel.getMarcasAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getMarcasResponse> getMarcasAsync(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getMarcasRequestBody();
            inValue.Body.cnpj = cnpj;
            return ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getMarcasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorNextGestorPDV.WSFinanceiro.getEmitenteResponse IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getEmitente(IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequest request) {
            return base.Channel.getEmitente(request);
        }
        
        public string getEmitente(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequestBody();
            inValue.Body.cnpj = cnpj;
            IntegradorNextGestorPDV.WSFinanceiro.getEmitenteResponse retVal = ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getEmitente(inValue);
            return retVal.Body.getEmitenteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getEmitenteResponse> IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getEmitenteAsync(IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequest request) {
            return base.Channel.getEmitenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getEmitenteResponse> getEmitenteAsync(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getEmitenteRequestBody();
            inValue.Body.cnpj = cnpj;
            return ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getEmitenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorNextGestorPDV.WSFinanceiro.getUsuarioResponse IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getUsuario(IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequest request) {
            return base.Channel.getUsuario(request);
        }
        
        public string getUsuario(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequestBody();
            inValue.Body.cnpj = cnpj;
            IntegradorNextGestorPDV.WSFinanceiro.getUsuarioResponse retVal = ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getUsuario(inValue);
            return retVal.Body.getUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getUsuarioResponse> IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getUsuarioAsync(IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequest request) {
            return base.Channel.getUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getUsuarioResponse> getUsuarioAsync(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getUsuarioRequestBody();
            inValue.Body.cnpj = cnpj;
            return ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasResponse IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.AtualizaVendas(IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequest request) {
            return base.Channel.AtualizaVendas(request);
        }
        
        public string AtualizaVendas(string cnpj, string chave, string json) {
            IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.chave = chave;
            inValue.Body.json = json;
            IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasResponse retVal = ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).AtualizaVendas(inValue);
            return retVal.Body.AtualizaVendasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasResponse> IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.AtualizaVendasAsync(IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequest request) {
            return base.Channel.AtualizaVendasAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasResponse> AtualizaVendasAsync(string cnpj, string chave, string json) {
            IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.AtualizaVendasRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.chave = chave;
            inValue.Body.json = json;
            return ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).AtualizaVendasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoResponse IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getFormaPgto(IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequest request) {
            return base.Channel.getFormaPgto(request);
        }
        
        public string getFormaPgto(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequestBody();
            inValue.Body.cnpj = cnpj;
            IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoResponse retVal = ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getFormaPgto(inValue);
            return retVal.Body.getFormaPgtoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoResponse> IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getFormaPgtoAsync(IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequest request) {
            return base.Channel.getFormaPgtoAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoResponse> getFormaPgtoAsync(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getFormaPgtoRequestBody();
            inValue.Body.cnpj = cnpj;
            return ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getFormaPgtoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasResponse IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getEtiquetas(IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequest request) {
            return base.Channel.getEtiquetas(request);
        }
        
        public string getEtiquetas(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequestBody();
            inValue.Body.cnpj = cnpj;
            IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasResponse retVal = ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getEtiquetas(inValue);
            return retVal.Body.getEtiquetasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasResponse> IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap.getEtiquetasAsync(IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequest request) {
            return base.Channel.getEtiquetasAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasResponse> getEtiquetasAsync(string cnpj) {
            IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequest inValue = new IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequest();
            inValue.Body = new IntegradorNextGestorPDV.WSFinanceiro.getEtiquetasRequestBody();
            inValue.Body.cnpj = cnpj;
            return ((IntegradorNextGestorPDV.WSFinanceiro.wsFinanceiroSoap)(this)).getEtiquetasAsync(inValue);
        }
    }
}
