namespace PDV.DAO.Custom
{
    public class ChavesConfiguracao
    {
        /* Configuração do DANFE */
        public static string CHAVE_CONFIGUACAODANFE_EMISSAONORMAL = "CONFIGUACAODANFE_EMISSAONORMAL";
        public static string CHAVE_CONFIGUACAODANFE_IMPRESSAOCONTINGENCIA = "CONFIGUACAODANFE_IMPRESSAOCONTINGENCIA";
        public static string CHAVE_CONFIGUACAODANFE_MARGEMIMPRESSAOESQUERDA = "CONFIGUACAODANFE_MARGEMIMPRESSAOESQUERDA";
        public static string CHAVE_CONFIGUACAODANFE_MARGEMIMPRESSAODIREITA = "CONFIGUACAODANFE_MARGEMIMPRESSAODIREITA";
        public static string CHAVE_CONFIGUACAODANFE_IMPRIMIRDESCONTOITEM = "CONFIGUACAODANFE_IMPRIMIRDESCONTOITEM";
        public static string CHAVE_CONFIGUACAODANFE_MODODEIMPRESSAO = "CONFIGUACAODANFE_MODODEIMPRESSAO";
        public static string CHAVE_CONFIGUACAODANFE_NOMEIMPRESSORA = "CONFIGUACAODANFE_NOMEIMPRESSORA";
        public static string CHAVE_CONFIGUACAODANFE_EXIBIRCAIXADIALOGO = "CONFIGUACAODANFE_EXIBIRCAIXADIALOGO";

        public static string CHAVE_CONFIGUACAODANFE_EMISSAONORMAL_NFE = "CONFIGUACAODANFE_EMISSAONORMAL_NFE";
        public static string METODO_SINCRONO = "METODO_SINCRONO";
        public static string CHAVE_CONFIGUACAODANFE_NOMEIMPRESSORA_NFE = "CONFIGUACAODANFE_NOMEIMPRESSORA_NFE";
        public static string CHAVE_CONFIGUACAODANFE_EXIBIRCAIXADIALOGO_NFE = "CONFIGUACAODANFE_EXIBIRCAIXADIALOGO_NFE";

        public static string CHAVE_CONFIGUACAODANFE_NOMEIMPRESSORA_MDFE = "CONFIGUACAODANFE_NOMEIMPRESSORA_MDFE";
        public static string CHAVE_CONFIGUACAODANFE_EXIBIRCAIXADIALOGO_MDFE = "CONFIGUACAODANFE_EXIBIRCAIXADIALOGO_MDFE";

        /* Confiuração dos WebServices */
        public static string CHAVE_NFCE_WEBSERVICE_AMBIENTE_PRODUCAO = "NFCE_WEBSERVICE_AMBIENTE_PRODUCAO";

        public static string CHAVE_NFCE_WEBSERVICE_RECEPCAOEVENTOCCECANCELAMENTO = "NFCE_WEBSERVICE_RECEPCAOEVENTOCCECANCELAMENTO";
        public static string CHAVE_NFCE_WEBSERVICE_RECEPCAOEVENTOEPEC = "NFCE_WEBSERVICE_RECEPCAOEVENTOEPEC";
        public static string CHAVE_NFCE_WEBSERVICE_RECEPCAOEVENTOMANIFESTACAODESTINATARIO = "NFCE_WEBSERVICE_RECEPCAOEVENTOMANIFESTACAODESTINATARIO";
        public static string CHAVE_NFCE_WEBSERVICE_NFERECEPCAO = "NFCE_WEBSERVICE_NFERECEPCAO";
        public static string CHAVE_NFCE_WEBSERVICE_NFERETRECEPCAO = "NFCE_WEBSERVICE_NFERETRECEPCAO";
        public static string CHAVE_NFCE_WEBSERVICE_NFEINUTILIZACAO = "NFCE_WEBSERVICE_NFEINUTILIZACAO";
        public static string CHAVE_NFCE_WEBSERVICE_NFECONSULTAPROTOCOLO = "NFCE_WEBSERVICE_NFECONSULTAPROTOCOLO";
        public static string CHAVE_NFCE_WEBSERVICE_NFESTATUSSERVICO = "NFCE_WEBSERVICE_NFESTATUSSERVICO";
        public static string CHAVE_NFCE_WEBSERVICE_NFECONSULTACADASTRO = "NFCE_WEBSERVICE_NFECONSULTACADASTRO";
        public static string CHAVE_NFCE_WEBSERVICE_NFEAUTORIZACAO = "NFCE_WEBSERVICE_NFEAUTORIZACAO";
        public static string CHAVE_NFCE_WEBSERVICE_NFERETAUTORIZACAO = "NFCE_WEBSERVICE_NFERETAUTORIZACAO";
        public static string CHAVE_NFCE_WEBSERVICE_NFEDISTRIBUICAODFE = "NFCE_WEBSERVICE_NFEDISTRIBUICAODFE";
        public static string CHAVE_NFCE_WEBSERVICE_NFECONSULTADEST = "NFCE_WEBSERVICE_NFECONSULTADEST";
        public static string CHAVE_NFCE_WEBSERVICE_NFEDOWNLOADNF = "NFCE_WEBSERVICE_NFEDOWNLOADNF";
        public static string CHAVE_NFCE_WEBSERVICE_ADMCSCNFCE = "NFCE_WEBSERVICE_ADMCSCNFCE";

        /* Protocolo de Segurança */
        public static string CHAVE_NFCE_PROTOCOLO_SEGURANCA_TLSOUSSL3 = "NFCE_PROTOCOLO_SEGURANCA_TLSOUSSL3";
        public static string CHAVE_NFCE_PROTOCOLO_SEGURANCA_TIMEOUT = "NFCE_PROTOCOLO_SEGURANCA_TIMEOUT";

        /* Configuração do Pedido de Venda */
        public static string CHAVE_CONFIGURACAOPEDIDOVENDA_NOMEIMPRESSORA = "CONFIGURACAOPEDIDOVENDA_NOMEIMPRESSORA";
        public static string CHAVE_CONFIGURACAOPEDIDOVENDA_EXIBIRCAIXADIALOGO = "CONFIGURACAOPEDIDOVENDA_EXIBIRCAIXADIALOGO";
        public static string CHAVE_CONFIGURACAOPEDIDOVENDA_DESCONTO_POR = "CONFIGURACAOPEDIDOVENDA_DESCONTO_POR";

        /* Configuração do Atualizador */
        public static string CHAVE_CONFIGURACAOATUALIZADOR_ENDERECO = "CONFIGURACAOATUALIZADOR_ENDERECO";
        public static string CHAVE_CONFIGURACAOATUALIZADOR_PASTA = "CONFIGURACAOATUALIZADOR_PASTA";
        public static string CHAVE_CONFIGURACAOATUALIZADOR_USUARIO = "CONFIGURACAOATUALIZADOR_USUARIO";
        public static string CHAVE_CONFIGURACAOATUALIZADOR_SENHA = "CONFIGURACAOATUALIZADOR_SENHA";

        /* Configuração do Android */
        public static string CHAVE_CONFIGURACAOANDROID_EXIBIRCATEGORIAPOR = "CONFIGURACAOANDROID_EXIBIRCATEGORIAPOR";
        public static string CHAVE_CONFIGURACAOANDROID_QUANTIDADE_MAXIMA_PRODUTO_COMANDA = "CONFIGURACAOANDROID_QUANTIDADE_MAXIMA_PRODUTO_COMANDA";

        /* Contingência */
        public static string CHAVE_CONFIGURACAOCONTINGENCIA_JUSTIFICATIVA = "CONFIGURACAOCONTINGENCIA_JUSTIFICATIVA";
        public static string CHAVE_CONFIGURACAOCONTINGENCIA_TEMPOINTERVALO_MOTOR = "CONFIGURACAOCONTINGENCIA_TEMPOINTERVALO_MOTOR";

        /* Login - Lembrar */
        public static string CHAVE_LOGIN_USUARIO_LEMBRAR = "LOGIN_USUARIO_LEMBRAR";
        public static string CHAVE_LOGIN_SENHA_LEMBRAR = "LOGIN_SENHA_LEMBRAR";

        /*TEF*/
        public static string TEF_CHAVE_AUTENTICACAO = "TEF_CHAVE_AUTENTICACAO";

        /*Natureza de operação Padrão NFCe*/
        public static string CHAVE_NFCE_NOME_NATUREZAOPERACAO = "CHAVE_NFCE_NATUREZAOPERACAO";
        public static string CHAVE_NFCE_CFOP_NATUREZAOPERACAO = "CHAVE_NFCE_CFOP_NATUREZAOPERACAO";

        //*Tipo de operação Padrão do app
        public static string TIPO_OPERACAO_PADRAO_APP = "TIPO_OPERACAO_PADRAO_APP";

        //*Tipo de operação Padrão do PDV
        public static string TIPO_OPERACAO_PADRAO_PDV = "TIPO_OPERACAO_PADRAO_PDV";
    }
}
